services:

  db:
    image: postgres:16
    container_name: moto_repuestos_db

    environment:
      POSTGRES_DB: moto_repuestos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.27
    container_name: moto_repuestos_liquibase

    depends_on:
      - db

    volumes:
      - ./:/liquibase/project

    working_dir: /liquibase/project

volumes:
  postgres_data: